### ISSUE TITLE
Feature Request: Add setting to enable/disable markdown syntax

### ISSUE THREAD

**Issue by EndlessDex** [Otard95/vscode-copy-reference#1]
Title.

**Comment by Otard95** [comment]
Have any specific format in mind? Is something like this fine:
```
<file>:<line>
<selection>
```

**Comment by Otard95** [comment]
I updated the extension, take a look see if you like it and get back to me

**Comment by Otard95** [comment]
Its implemented, maybe not in the exact way you wanted, but implemented. So I'm closing the issue

**Comment by EndlessDex** [comment]
That's amazing! Thank you so much :D

Sorry I didn't reply sooner. The format you went with is perfect.
