### ISSUE TITLE
[feature request] toggle including project name/notification

### ISSUE THREAD

**Issue by LutherZhao** [Otard95/vscode-copy-reference#2]
Hi, thank you for this extension it is very useful. I have a small request - can you add a setting to 
1. not include <project name>; only have "path/to/file:<line>". Context: I use this for quickly getting breakpoint locations, and the project name confuses gdb. 
2. disable the "Copied to clipboard" notification. Since I use this extension a lot, the notification can block parts of the screen that I have to manually dismiss. 

Thank you

**Comment by Otard95** [comment]
Hi there! I don't actively work on this plugin anymore as I've started using Neovim fulltime.
But I'll see what I can do when and if i get to it. Of course you are always welcome to create a PR for the issue, and I'll take a look at it!

**Comment by Otard95** [comment]
I've published and update that I hope satisfies your needs.

**Comment by LutherZhao** [comment]
thank you! I'll give it a try

**Comment by LutherZhao** [comment]
works great
